PROJECT_NAME := carbon-carp_default-4rx
REVISION := rev4.2
M_CUSTOM_LIBS :=
M_ADI_LIBS :=
M_REPOS := hdl-compat-default-4rx-carbon
M_DEPS :=

include ../../../common/carbon-carp/$(REVISION)/scripts/carbon-carp.mk
include ../../scripts/default-4rx_proj.mk
