PROJECT_NAME := carbon_default-4rx
REVISION := rev3
M_CUSTOM_LIBS :=
M_ADI_LIBS :=
M_REPOS := hdl-compat-default-4rx-carbon
M_DEPS :=

include ../../../common/carbon/$(REVISION)/scripts/carbon.mk
include ../../scripts/default-4rx_proj.mk
